### ISSUE TITLE
Outbound webhook?

### ISSUE THREAD

**Issue by petemounce** [lever/postings-api#26]
Hi there. I wonder whether you already have an outbound webhook for referral/candidate status changes? We restrict people from viewing the full details of referrals and candidates, but would find it useful to let people know when one of the people they're following has had an update. A webhook would allow that to be dropped into, say, a slack channel (or anything else one might like).

I'd want the outbound request to have data like

```yaml
---
candidate:
  id: <blah>
  # intentionally don't put personally-identifying information in the request 
  # because of impending GDPR - integrators would need to GET data that they need
role:
  id: <blah>
  <maybe some attributes about the role to save the 
    integrator needing to do a request to your API>
status:
  previous:
    name: referred #enum of statuses
  now:
    name: archived
  reason: "Not looking right now" #free text
```

I'm using yaml to illustrate, not to ask for the format to be yaml.

The PII bit might be a concern already simply because of the candidate id being a `UserID`; you'd need to have [a look at the regulations](https://ico.org.uk/for-organisations/data-protection-reform/overview-of-the-gdpr/).
